config/routes.rb
Rails.application.routes.draw do

  devise_for :clients, controllers: {
    sessions: "clients/sessions",
    registrations: "clients/registrations"
  }
  devise_for :admins, controllers: {
    sessions: "admins/sessions"
  }
  root to: 'static_pages#index'

  resources :restaurants
  resources :keywords
  resources :dishes

end

app/models/dish.rb
class Dish < ApplicationRecord
  belongs_to :restaurant, class_name: "Restaurant", foreign_key: "restaurant_id"
  has_many :kewworddishes, class_name: "KewwordDish"

  mount_uploader :avatar, AvatarUploader

end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
before_action :authenticate_client!
  def new
    @dish = Dish.new
    @restaurant = Restaurant.all
    @keyword = Keyword.all
    @dish.kewworddishes.build
  end

  def index
    @dish = Dish.all
  end

  def create
    @checked = params[:keywords]
    puts @checked
    puts "TEST"
    @dish = Dish.new(dish_params)
    @checked.each do |ch|
      puts "HERE"
      puts ch
      @keyword = KewwordDish.find_by keyword_id: ch
      puts @keyword
      if @keyword
        @dish.kewworddishes << @keyword
      end
    end
    if @dish.save
      #@dish.kewworddishes.build(keyword_id: params[:dish][keyword_id:[]])
      if @dish.save
        flash[:success] = "created. Ok"
        redirect_to dishes_path
      else
        @restaurant = Restaurant.all
        @keyword = Keyword.all
        flash[:error] = "Houston we are in troubles, try it again."
        render 'new'
      end
    else
      @restaurant = Restaurant.all
      @dish.kewworddishes.nil? ? @dish.kewworddishes.build : nil
      flash[:error] = "Error...."
      render 'new'
    end
  end

  def edit
    find_dish
    @restaurant = Restaurant.all
    @keyword = Keyword.all
    if @dish.nil?
      flash[:error] = "Houston we are in troubles, please dont hack us."
      redirect_to dishes_path
    end
  end

  def update
    find_dish
    if @dish.update(dish_params)
      flash[:success] = "updated. Ok"
      redirect_to dishes_path
    else
      flash[:error] = "Houston we are in troubles, try it again."
      render 'edit'
    end
  end

  def destroy
    find_dish
    if @dish.destroy
      flash[:success] = "Destroyed Successfully"
    else
      flash[:error] = "Houston we are in troubles, please try it later"
    end
    redirect_to dishes_path
  end

  def show
    find_dish
    if @dish.nil?
      flash[:error] = "Houston we are in troubles, please dont hack us."
      redirect_to dishes_path
    end
  end

  private

  def find_dish
    @dish = Dish.find_by(id: params[:id])
  end

  def dish_params
    params.require(:dish).permit(:restaurant_id, :name, :avatar)
  end

end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/views/dishes/_form.html.erb
<% form_name ||= "Manage" %>
<h1 class="text-center">  <%= form_name %> Dish </h1>
<!--<div id="notebook-errors-messages" style="display:none;"></div>-->
<div id="form_dish">
<%= form_for @dish , method: (form_name.downcase == 'edit' ? 'put' : 'post') do |fc| %>

    <% if @dish.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@dish.errors.count, "error") %> prohibited
          this article from being saved:
        </h2>
        <ul>
          <% @dish.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

  <div class="form-group" style="width: 400px">
    <%= fc.label :restaurant_id %>
    <br>
    <%= fc.select(:restaurant_id) do  %>
        <% @restaurant.each do |c| %>
          <%= content_tag(:option, c.name, value: c.id) %>
        <% end %>
      <% end %>
  </div>

  <div class="form-group" style="width: 400px">
    <%= fc.label :name %>
    <%= fc.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group" style="width: 400px">
    <%= fc.label :avatar %>
    <%= fc.file_field :avatar, class: "form-control" %>
  </div>
  <label>Key words</label>

  <div class="form-group" style="width: 400px" >
    <select name="dish[keyword_id]" id="select_dish">
      <% @keyword.each do |m| %>
        <option value="<%= m.id %>"> <%= m.name %></option>
      <% end %>
    </select>
  <ul class="list-group checked-list-box">
    <% @keyword.each do |keyword| %>
        <li class="list-group-item" data-color="success">
          <%= check_box_tag "keywords[]", keyword.id, false %>
          <%= h keyword.name %>
        </li>
    <% end %>
  </ul>


  <%= fc.submit "#{form_name} dish", class: "btn btn-primary" %>
  <a href="<%= dishes_path %>" class="btn btn-default"> View all </a>
<% end %>
</div>

app/views/dishes/edit.html.erb
<div class="container">
  <%= render "form" , form_name: params[:action].capitalize %>
</div>

app/views/dishes/index.html.erb
<div class="container">
  <h1 class="text-center"> Dish </h1>

    <section class="row text-center cities-controls" id="notebook-actions">
        <a href="<%= new_dish_path %>" class="btn btn-default" > New Dish </a>
    </section>

    <% @dish.each do |f| %>
    <div class="col-md-4">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title"><%= f.restaurant.name %>
          <span class="pull-right clickable"><i class="glyphicon glyphicon-chevron-up"></i></span></h3>
        </div>
        <div class="panel-body" style="height: 344px">
          <div class="text-center"><h4><li class="list-unstyled"><%= f.name %></li></h4></div>
          <li class="list-unstyled"><img src="<%= f.avatar %>" class="img_dish" alt="product"></li>
          <div class="menu_dish text-center">
            <a href="<%= dish_path(f.id) %>" data-method="delete" class="btn btn-danger"> Delete </a>
            <a href="<%= edit_dish_path(f.id) %>" class="btn btn-primary"> Edit </a>
            <a href="<%= dish_path(f.id) %>" class="btn btn-info" > Show </a>
          </div>
        </div>
      </div>
    </div>
    <% end if @dish.any? %>

  </div>

app/views/dishes/new.html.erb
<div class="container">
  <%= render "form" , form_name: params[:action].capitalize %>
</div>

app/views/dishes/show.html.erb
<div class="container">
  <article class="row city">
    <ul>
      <li class="col-md-2 list-unstyled"><strong><%= @dish.name %></strong></li>
      <li class="col-md-2 list-unstyled"><strong><img src="<%= @dish.avatar %>" class="img_dish" alt="product"></strong></li>
      <li class="col-md-2 list-unstyled"><a href="<%= dish_path(@dish.id) %>" data-method="delete" class="btn btn-danger"> Delete </a></li>
    </ul>
  </article>
</div>