config/routes.rb
Rails.application.routes.draw do

  devise_for :clients, controllers: {
    sessions: "clients/sessions",
    registrations: "clients/registrations"
  }
  devise_for :admins, controllers: {
    sessions: "admins/sessions"
  }
  root to: 'static_pages#index'

  resources :restaurants
  resources :keywords
  resources :dishes

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :user, class_name: "User", foreign_key: "user_id"
  has_many :scores, class_name: "Score"
  has_many :dishes, class_name: "Dish"
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :authenticate_client!
  def index
     @restaurants = Restaurant.all

  end

  def new
    @restaurant = Restaurant.new
  end

  def edit
    find_restaurant
    if @restaurant.nil?
      flash[:error] = "Houston we are in troubles, please dont hack us."
      redirect_to root_path
    end
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.user_id = current_client.id
    if @restaurant.save
      redirect_to restaurants_path
    else
      flash[:success] = "Restaurant created. Ok"
      render 'new'
    end
  end

  def destroy
    find_restaurant
    if @restaurant.destroy
      flash[:success] = "Restaurant Destroyed Successfully"
    else
      flash[:error] = "Houston we are in troubles, please try it later"
    end
    redirect_to restaurants_path
  end

  def update
    find_restaurant
    if @restaurant.update(restaurant_params)
      flash[:success] = "Restaurant updated. Ok"
      redirect_to restaurants_path
    else
      flash[:error] = "Houston we are in troubles, try it again."
      render 'edit'
    end
  end


  def show
    find_restaurant
    if @restaurant.nil?
      flash[:error] = "Houston we are in troubles, please dont hack us."
      redirect_to root_path
    end
  end

  private

  def find_restaurant
    @restaurant = Restaurant.find_by(id: params[:id])
  end

  #strong parameters
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :gps, :image)
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_formNewEdit.html.erb
<% content_for :javascript_includes do %>
  <%= javascript_include_tag "restaurants2.js" %>
<% end %>
<div class="container" id="container_restaurant">
  <h1 class="text-center">  Create Restaurant</h1>
  <%= form_for @restaurant do |f| %>
  <% if @restaurant.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@restaurant.errors.count, "error") %> prohibited
      this article from being saved:
    </h2>
    <ul>
      <% @restaurant.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <div class="form-group">
    <%= f.label :name%>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :address%>
    <%= f.text_field :address, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :gps%>
    <%= f.text_field :gps, class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <%= f.submit "Create Restaurant", class: "btn btn-primary" %>
  <a href="<%= restaurants_path %>" class="btn btn-default"> View all </a>
  <% end %>
</div>
<div id="map">
</div>

app/views/restaurants/delete.html.erb
<h1>Restaurants#delete</h1>
<p>Find me in app/views/restaurants/delete.html.erb</p>

app/views/restaurants/edit.html.erb
<h1>Restaurants#edit</h1>
<p>Find me in app/views/restaurants/edit.html.erb</p>

app/views/restaurants/index.html.erb
<% content_for :javascript_includes do %>
<%= javascript_include_tag "restaurants.js" %>
<% end %>
<h1 class="text-center" id="title_luch">Ubication!! </h1>
<h4 class="text-center">Your favorite place </h4>
<div class="list_restaurants">
  <% @restaurants.each do |f| %>
  <article class="">
    <ul class="table-results">
      <div class="results-row">
        <li class="list-group-item list-group-item-action list-group-item-danger"><span class="glyphicon glyphicon-cutlery"></span> <%= f.name %></li>
      </ul>
    </article>
    <% end if @restaurants.any? %>
  </div>
  <% r_string = "[" %>
  <% @restaurants.each do |r| %>
  <% r_string += "[\"#{r.name}\",#{r.gps}]" %>
  <% if !r.equal?(@restaurants.last)%>
  <% r_string += "," %>
  <% end %>
  <% end %>
  <% r_string += "]" %>

  <section id="content_map">
    <div id="map" data-url="show" data-gps="<%= r_string %>">
    </div>
  </section>

app/views/restaurants/new.html.erb
<div class="container">
  <%= render "formNewEdit" , form_name: params[:action].capitalize %>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <article class="row city">
    <ul>
      <li class="col-md-2"><strong><%= @restaurant.name %></strong></li>
      <li class="col-md-2"><strong><%= @restaurant.address %></strong></li>
      <li class="col-md-2"><strong><%= @restaurant.image %></strong></li>
      <li class="col-md-2" id="gps_show"><strong><%= @restaurant.gps %></strong></li>
      <li class="col-md-2"><a href="<%= restaurant_path(@restaurant.id) %>" data-method="delete" class="btn btn-danger"> Delete </a></li>
    </ul>
  </article>
</div>
<div id="map" data-url="show">
</div>