config/routes.rb
Rails.application.routes.draw do

  devise_for :clients, controllers: {
    sessions: "clients/sessions",
    registrations: "clients/registrations"
  }
  devise_for :admins, controllers: {
    sessions: "admins/sessions"
  }
  root to: 'static_pages#index'

  resources :restaurants
  resources :keywords
  resources :dishes

end

app/models/keyword.rb
class Keyword < ApplicationRecord
  has_many :kewworddishes, class_name: "KewwordDish"
end

app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController
before_action :authenticate_client!
  def new
    @keyword = Keyword.new
  end

  def index
    @keyword = Keyword.all
  end

  def create
    @keyword = Keyword.new(keyword_params)
    if @keyword.save
      flash[:success] = "created. Ok"
      redirect_to keywords_path
    else
      flash[:error] = "Houston we are in troubles, try it again."
      render 'new'
    end
  end

  def edit
    find_keyword
    if @keyword.nil?
      flash[:error] = "Houston we are in troubles, please dont hack us."
      redirect_to keywords_path
    end
  end

  def update
    find_keyword
    if @keyword.update(keyword_params)
      flash[:success] = "updated. Ok"
      redirect_to keywords_path
    else
      flash[:error] = "Houston we are in troubles, try it again."
      render 'edit'
    end
  end

  def destroy
    find_keyword
    if @keyword.destroy
      flash[:success] = "Destroyed Successfully"
    else
      flash[:error] = "Houston we are in troubles, please try it later"
    end
    redirect_to keywords_path
  end

  def show
    find_keyword
    if @keyword.nil?
      flash[:error] = "Houston we are in troubles, please dont hack us."
      redirect_to keywords_path
    end
  end

  private

  def find_keyword
    @keyword = Keyword.find_by(id: params[:id])
  end

  def keyword_params
    params.require(:keyword).permit(:name)
  end

end

app/helpers/keywords_helper.rb
module KeywordsHelper
end

app/views/keywords/_form.html.erb
<% form_name ||= "Manage" %>
<h1 class="text-center">  <%= form_name %> Keyword </h1>
<!--<div id="notebook-errors-messages" style="display:none;"></div>-->
<%= form_for @keyword , method: (form_name.downcase == 'edit' ? 'put' : 'post') do |fc| %>

    <% if @keyword.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@keyword.errors.count, "error") %> prohibited
          this article from being saved:
        </h2>
        <ul>
          <% @keyword.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

  <div class="form-group">
    <%= fc.label :name %>
    <%= fc.text_field :name, class: "form-control" %>
  </div>

  <%= fc.submit "#{form_name} keyword", class: "btn btn-primary" %>

<% end %>
<a href="<%= keywords_path %>" class="btn btn-default"> View all </a>

app/views/keywords/edit.html.erb
<div class="container">
  <%= render "form" , form_name: params[:action].capitalize %>
</div>

app/views/keywords/index.html.erb
<div class="container">
  <h1 class="text-center"> Keywords </h1>
  <% if current_user %>
    <section class="row text-center cities-controls" id="notebook-actions">
        <a href="<%= new_keyword_path %>" class="btn btn-default" > New Keywords </a>
    </section>
  <% end %>
  <% @keyword.each do |f| %>
    <article class="">
      <ul class="table-results">
        <table class="table table-striped">


    
          <td class="results-cell results-aling result-title list-unstyled"><%= f.name %></td>

            <td class="results-cell list-unstyled"><a href="<%= keyword_path(f.id) %>" data-method="delete" class="btn btn-danger"> Delete </a></td>
            <td class="results-cell list-unstyled"><a href="<%= edit_keyword_path(f.id) %>" class="btn btn-primary"> Edit </a></td>
            <td class="results-cell list-unstyled"><a href="<%= keyword_path(f.id) %>" class="btn btn-info" > Show </a></td>
        </div>
        </table>

      </ul>
    </article>
  <% end if @keyword.any? %>
</div>

app/views/keywords/new.html.erb
<div class="container">
  <%= render "form" , form_name: params[:action].capitalize %>
</div>

app/views/keywords/show.html.erb
<div class="container">
  <article class="">
    <ul class="table-results">
      <div class="result-row">
        <li class="results-cell result-aling result-title"><%= @keyword.name %></li>
      </div>
      <% if current_user %>
      <div class="result-row text-center">
        <li class=""class="results-cell"><a href="<%= keyword_path(@keyword.id) %>" data-method="delete" class="btn btn-danger"> Delete </a></li>
      </div>
      <% end %>
    </ul>
  </article>
</div>
<section class="row text-center cities-controls">

</section>