config/routes.rb
Rails.application.routes.draw do

  devise_for :clients, controllers: {
    sessions: "clients/sessions",
    registrations: "clients/registrations"
  }
  devise_for :admins, controllers: {
    sessions: "admins/sessions"
  }
  root to: 'static_pages#index'

  resources :restaurants
  resources :keywords
  resources :dishes

end

app/models/admin.rb
class Admin < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < User
end

app/models/dish.rb
class Dish < ApplicationRecord
  belongs_to :restaurant, class_name: "Restaurant", foreign_key: "restaurant_id"
  has_many :kewworddishes, class_name: "KewwordDish"

  mount_uploader :avatar, AvatarUploader

end

app/models/kewword_dish.rb
class KewwordDish < ApplicationRecord
  belongs_to :dish, class_name: "Dish", foreign_key: "dish_id"
  belongs_to :keyword, class_name: "Keyword", foreign_key: "keyword_id"
end

app/models/keyword.rb
class Keyword < ApplicationRecord
  has_many :kewworddishes, class_name: "KewwordDish"
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :user, class_name: "User", foreign_key: "user_id"
  has_many :scores, class_name: "Score"
  has_many :dishes, class_name: "Dish"
end

app/models/score.rb
class Score < ApplicationRecord
  belongs_to :user, class_name: "User", foreign_key: "user_id"
  belongs_to :restaurant, class_name: "Restaurant", foreign_key: "restaurant_id"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :restaurants, class_name: "Restaurant"
  has_many :scores, class_name: "Score"


end

app/controllers/admins/unlocks_controller.rb
class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def current_user
    @current_user = current_admin ? current_admin : current_client ? current_client : nil
  end
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
before_action :authenticate_client!
  def new
    @dish = Dish.new
    @restaurant = Restaurant.all
    @keyword = Keyword.all
    @dish.kewworddishes.build
  end

  def index
    @dish = Dish.all
  end

  def create
    @checked = params[:keywords]
    puts @checked
    puts "TEST"
    @dish = Dish.new(dish_params)
    @checked.each do |ch|
      puts "HERE"
      puts ch
      @keyword = KewwordDish.find_by keyword_id: ch
      puts @keyword
      if @keyword
        @dish.kewworddishes << @keyword
      end
    end
    if @dish.save
      #@dish.kewworddishes.build(keyword_id: params[:dish][keyword_id:[]])
      if @dish.save
        flash[:success] = "created. Ok"
        redirect_to dishes_path
      else
        @restaurant = Restaurant.all
        @keyword = Keyword.all
        flash[:error] = "Houston we are in troubles, try it again."
        render 'new'
      end
    else
      @restaurant = Restaurant.all
      @dish.kewworddishes.nil? ? @dish.kewworddishes.build : nil
      flash[:error] = "Error...."
      render 'new'
    end
  end

  def edit
    find_dish
    @restaurant = Restaurant.all
    @keyword = Keyword.all
    if @dish.nil?
      flash[:error] = "Houston we are in troubles, please dont hack us."
      redirect_to dishes_path
    end
  end

  def update
    find_dish
    if @dish.update(dish_params)
      flash[:success] = "updated. Ok"
      redirect_to dishes_path
    else
      flash[:error] = "Houston we are in troubles, try it again."
      render 'edit'
    end
  end

  def destroy
    find_dish
    if @dish.destroy
      flash[:success] = "Destroyed Successfully"
    else
      flash[:error] = "Houston we are in troubles, please try it later"
    end
    redirect_to dishes_path
  end

  def show
    find_dish
    if @dish.nil?
      flash[:error] = "Houston we are in troubles, please dont hack us."
      redirect_to dishes_path
    end
  end

  private

  def find_dish
    @dish = Dish.find_by(id: params[:id])
  end

  def dish_params
    params.require(:dish).permit(:restaurant_id, :name, :avatar)
  end

end

app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController
before_action :authenticate_client!
  def new
    @keyword = Keyword.new
  end

  def index
    @keyword = Keyword.all
  end

  def create
    @keyword = Keyword.new(keyword_params)
    if @keyword.save
      flash[:success] = "created. Ok"
      redirect_to keywords_path
    else
      flash[:error] = "Houston we are in troubles, try it again."
      render 'new'
    end
  end

  def edit
    find_keyword
    if @keyword.nil?
      flash[:error] = "Houston we are in troubles, please dont hack us."
      redirect_to keywords_path
    end
  end

  def update
    find_keyword
    if @keyword.update(keyword_params)
      flash[:success] = "updated. Ok"
      redirect_to keywords_path
    else
      flash[:error] = "Houston we are in troubles, try it again."
      render 'edit'
    end
  end

  def destroy
    find_keyword
    if @keyword.destroy
      flash[:success] = "Destroyed Successfully"
    else
      flash[:error] = "Houston we are in troubles, please try it later"
    end
    redirect_to keywords_path
  end

  def show
    find_keyword
    if @keyword.nil?
      flash[:error] = "Houston we are in troubles, please dont hack us."
      redirect_to keywords_path
    end
  end

  private

  def find_keyword
    @keyword = Keyword.find_by(id: params[:id])
  end

  def keyword_params
    params.require(:keyword).permit(:name)
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :authenticate_client!
  def index
     @restaurants = Restaurant.all

  end

  def new
    @restaurant = Restaurant.new
  end

  def edit
    find_restaurant
    if @restaurant.nil?
      flash[:error] = "Houston we are in troubles, please dont hack us."
      redirect_to root_path
    end
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.user_id = current_client.id
    if @restaurant.save
      redirect_to restaurants_path
    else
      flash[:success] = "Restaurant created. Ok"
      render 'new'
    end
  end

  def destroy
    find_restaurant
    if @restaurant.destroy
      flash[:success] = "Restaurant Destroyed Successfully"
    else
      flash[:error] = "Houston we are in troubles, please try it later"
    end
    redirect_to restaurants_path
  end

  def update
    find_restaurant
    if @restaurant.update(restaurant_params)
      flash[:success] = "Restaurant updated. Ok"
      redirect_to restaurants_path
    else
      flash[:error] = "Houston we are in troubles, try it again."
      render 'edit'
    end
  end


  def show
    find_restaurant
    if @restaurant.nil?
      flash[:error] = "Houston we are in troubles, please dont hack us."
      redirect_to root_path
    end
  end

  private

  def find_restaurant
    @restaurant = Restaurant.find_by(id: params[:id])
  end

  #strong parameters
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :gps, :image)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user
    @current_user = current_admin ? current_admin : current_client ? current_client : nil
  end
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/keywords_helper.rb
module KeywordsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LunchTime!!</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBElfba4JgUAu78FJ9Tyxhq-sXwvz9H8mo&callback=initMap"  defer></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= yield :javascript_includes%>
</head>


<header class="container-head">
  <div class="">
    <img src="https://s30.postimg.org/4tljbcmvl/logo2.png" alt="Logo_pagina">
  </div>
  <nav class="menu-nav">
    <a class="navbar-brand logo-link" href="<%= root_path %>"><span class="glyphicon glyphicon-home"></span> Home</a>
    <% if current_user %>
    <span class="navbar-brand logo-link"> User: <%= current_user.email %> </span>
    <% end %>
    <ul class="nav navbar-nav navbar-right">
      <% if !current_user %>
      <li><a href="<%= new_client_session_path %>" class="menu-option"><span class="glyphicon glyphicon-user"></span> Log in</a></li>
      <li><a href="<%= new_client_registration_path %>" class="menu-option"><span class="glyphicon glyphicon-user"></span> Sign up</a></li>
      <% else %>
      <li><a href="<%= restaurants_path %>" class="menu-option"><span class="glyphicon glyphicon-chevron-right"></span> Search </a></li>
      <li><a href="<%= new_restaurant_path %>" class="menu-option"><span class="glyphicon glyphicon-chevron-right"></span> Restaurant </a></li>
      <li><a href="<%= new_dish_path %>" class="menu-option"><span class="glyphicon glyphicon-chevron-right"></span> Dishes </a></li>
      <li><a href="<%= new_keyword_path %>" class="menu-option"><span class="glyphicon glyphicon-chevron-right"></span> Keywords </a></li>
      <li><a href="<%= dishes_path %>" class="menu-option"><span class="glyphicon glyphicon-chevron-right"></span> Index Dishes </a></li>
      <li ><a href="<%= destroy_client_session_path %>" class="menu-option" data-method="delete">Log out</a></li>
      <% end %>
    </ul>
  </div>
</nav>

</header>


<div class="container-main">
  <% if flash[:success] or flash[:error] or flash[:notice]%>
  <span class="flash-message <%= flash[:success] ? 'success alert glyphicon glyphicon-ok-circle' : flash[:error] ? 'error alert glyphicon glyphicon-remove-circle' : flash[:notice] ? 'notice alert glyphicon glyphicon-info-sign' : '' %>">
    <%= flash[:success] ? flash[:success] : flash[:error] ? flash[:error] : flash[:notice] ? flash[:notice] : '' %>
  </span>
  <% end %>
</div>

<%= yield %>

</body>
</html>